# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  socket-vmnet-sources = {
    pname = "socket-vmnet-sources";
    version = "v1.1.7";
    src = fetchFromGitHub {
      owner = "lima-vm";
      repo = "socket_vmnet";
      rev = "v1.1.7";
      fetchSubmodules = false;
      sha256 = "sha256-SABFfeMhabz1MIBCyzV6kErR0xdtP4fX1zQOagO7lVA=";
    };
  };
}
