# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  socket-vmnet-sources = {
    pname = "socket-vmnet-sources";
    version = "v1.2.1";
    src = fetchFromGitHub {
      owner = "lima-vm";
      repo = "socket_vmnet";
      rev = "v1.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-MbmfCS8gG7XVbG7mVXGen7F/chEIyTvWSoHfwIiF+2s=";
    };
  };
}
